version: "3"

networks:
  tb:
    driver: bridge

services:
  ros:
    build: ""
    # stdin_open: true
    # tty: true
    networks:
      - tb

  feagi:
    build: ../../../docker
    environment:
      - CONTAINERIZED=true
    networks:
      - tb
